### ISSUE TITLE
Migrera projektet till ett monorepo med `nx`

### ISSUE THREAD

**Issue by edenstrom** [kolplattformen/skolplattformen#497]
Denna issue är in progress.

Planen är att kombinera ett antal av våra repositories. Målet är att göra det lättare att bryta ut gemensam funktionalitet när projektet växer, samt att slippa mellanlanda ändringar i `npm`-registret.

## TODO

- [x] mergea `kolplattformen/skolplattformen`
- [x] mergea `kolplattformen/api-hooks` till `libs/hooks`
- [x] mergea `kolplattformen/embedded-api` till `libs/api-skolplattformen`
- [x] mergea `kolplattformen/curriculum` till `libs/curriculum`
- [x] All historik ska vara kvar
- [x] Flytta `packages/app` till `apps/skolplattformen-sthlm`
- [x] Flytta `packages/site` till `apps/website`
- [x] Installera `nx` och få in rätt konfiguration. Finns en del i `feature/ng-migration`
- [x] Centralisera dependencies som `nx` rekommenderar
- [x] Centralisera `tsconfig.json` så att alla använder samma
- [x] Skriv om `apps/skolplattformen-sthlm/library-extractor.js` att använda rätt package.json. Ska denna centraliseras så att det går att använda i fler projekt? Kanske under tools?
- [x] Konfigurera/patcha ui-kitten så att det fungerar korrekt
- [ ] Fixa tester som failar

Efter migreringen ska det gå att köra `nx start` samt `nx run-ios`. Appen ska bygga och köras utan fel. Kontrollera att bitrise-byggen fungerar.

**Comment by edenstrom** [comment]
Fixed in #479 #506
